- hosts: localhost
  tasks:
    - name: "Install apache2"
      apt: name=apache2 state=present
    - name: "Install php"
      apt: name=php state=present
    - name: "Install php-mysql"
      apt: name=php-mysql state=present

    - name: Download and Extract WorPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes


    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: mv
      shell: mv /var/www/html/wordpress/*  /var/www/html/

    - name: rm
      command: rm -rf /var/www/html/wordpress

    - name: Update Wordpress config file
      lineinfile:
        path: /var/www/html/wp-config-sample.php
        regexp: "{{item.regexp}}"
        line: "{{item.line}}"
      with_items:
        - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', 'wordpress' );"}
        - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', 'wordpress' );"}
        - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', 'wordpress123' );"}
        - {'regexp': "define\\( 'DB_HOST', '(.)+' \\);", 'line': "define( 'DB_HOST', 'wordpress.cnwunojhu2of.ap-south-1.rds.amazonaws.com
' );"}

    - name: per
      command: chmod -R 755 /var/www/html/wp-content

    - name: per2
      command: chown -R www-data:www-data /var/www/html/

    - name: per3
      command: chown -R www-data:www-data /var/www/html/wp-content/


